# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pr: none

variables:
  - group: awsterragitazure

parameters:
  - name: action
    displayName: "Type action: start | destroy"
    type: string
    default: start
    values:
      - start
      - destroy

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: |
      ls -R
    displayName: "Show Repo Structure"

  - script: |
      aws sts get-caller-identity
    displayName: "Verify AWS Credentials"
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: ap-south-1

  - script: |
      echo "Checking key file..."
      ls -l ec2-key.pem
      head -2 ec2-key.pem
    displayName: "Verify PEM File"

  - task: TerraformInstaller@1
    displayName: "Install Terraform"
    inputs:
      terraformVersion: latest

  - script: |
      rm -rf .terraform
      rm -f .terraform.lock.hcl
    displayName: "Clean Terraform Cache"

  - script: |
      terraform init -reconfigure
    displayName: "Terraform Init"
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: ap-south-1

  - script: |
      terraform validate
    displayName: "Terraform Validate"

  - script: |
      terraform plan
    displayName: "Terraform Plan"
    condition: eq('${{ parameters.action }}', 'start')
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: ap-south-1

  - script: |
      terraform apply -auto-approve
    displayName: "Terraform Apply"
    condition: eq('${{ parameters.action }}', 'start')
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: ap-south-1

  - script: |
      terraform destroy -auto-approve
    displayName: "Terraform Destroy"
    condition: eq('${{ parameters.action }}', 'destroy')
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: ap-south-
      